spring:
  application:
    name: departmentservice
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    fetch-registry: true
    register-with-eureka: true